# Generated by Django 2.1.1 on 2019-02-01 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField()),
                ('what', models.CharField(max_length=150)),
                ('where', models.CharField(max_length=250)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100)),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('active_member', models.BooleanField(default=True)),
                ('semesters_active', models.CharField(max_length=100)),
                ('twitter_url', models.URLField()),
                ('github_url', models.URLField()),
                ('linkedin_url', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('website_url', models.URLField()),
                ('expected_graduation', models.CharField(max_length=50)),
                ('internship_interest', models.CharField(max_length=50)),
                ('cs_interests', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('time_posted', models.DateTimeField(auto_now=True)),
                ('last_updated', models.DateTimeField()),
                ('body', models.TextField()),
                ('related_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('repo_url', models.URLField()),
                ('description', models.TextField()),
                ('future_state', models.TextField()),
                ('researchers', models.ManyToManyField(to='backend.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.TextField()),
                ('publication_url', models.URLField()),
            ],
        ),
    ]
