# Generated by Django 2.1.1 on 2019-02-02 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_member_newgrad_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='headshot',
            field=models.ImageField(default=2, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
