# Generated by Django 2.1.1 on 2019-02-02 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_member_headshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='headshot',
            field=models.ImageField(default='default.png', upload_to='uploads/'),
        ),
    ]
