# Generated by Django 2.1.1 on 2019-02-02 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20190202_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='cs_interests',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='github_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='linkedin_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='twitter_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='website_url',
            field=models.URLField(null=True),
        ),
    ]
