# Generated by Django 2.1.1 on 2019-02-10 21:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20190209_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='date_of_grant',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='publication',
            name='date_of_publication',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='news',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='time_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='future_state',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='researchers',
            field=models.TextField(blank=True, null=True),
        ),
    ]
